apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: authorizer-visa
  annotations:
    prometheus.io/rule: 'Watchdog'
    prometheus.io/rule: node_memory_Active_bytes|instance
  tags:
    - dotnet
    - microservice
spec:
  type: service
  lifecycle: production
  owner: authorizer-team
  system: authorization
  providesApis:
    - authorizer-visa
  dependsOn:
    - Component:transactions
    
---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: authorizer-visa
spec:
  type: openapi
  lifecycle: production
  owner: authorizer-team
  system: authorization
  definition:
    $text: ./openapi.json
